###################################################################
# This are the levels of the catalan game at:                     #
#     https://ded.increpare.com/~locus/catalan/                   #
# transformed in a MedØlDatschgerl compatible format.             #
# The graphGMLStrings are written in GML.                         #
# Also look at:                                                   #
#     http://www.increpare.com/2011/01/catalan/                   #
# The levels are taken from catalan_src/src/data/levels.txt from: #
#     http://ded.increpare.com/~locus/catalan_src.zip             #
###################################################################

SUCCESS = graphGMLString("""
graph [
    node[id 0 label "0"]
]
""", name="SUCCESS")

FIRST_LEVEL = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 2 label ""]
    edge[source 0 target 3 label ""]
]
""", name="FIRST LEVEL")

K2 = graphGMLString("""
graph[
    node[id 0 label "0"]
    node[id 1 label "0"]
    edge[source 0 target 1 label ""]
]
""", name="K2")

N3E1 = graphGMLString("""
graph[
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    edge[source 0 target 1 label ""]
]
""", name="N3E1")

N3E2 = graphGMLString("""
graph[
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 2 target 1 label ""]
]
""", name="N3E2")


K3 = graphGMLString("""
graph[
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 2 target 1 label ""]
    edge[source 0 target 2 label ""]
]
""", name="K3")


SIMPLE_BLOSSOM = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 2 label ""]
    edge[source 1 target 3 label ""]
    edge[source 3 target 2 label ""]
    edge[source 4 target 0 label ""]
    edge[source 0 target 5 label ""]
    edge[source 5 target 6 label ""]
    edge[source 6 target 7 label ""]
    edge[source 7 target 0 label ""]
    edge[source 0 target 8 label ""]
    edge[source 8 target 9 label ""]
    edge[source 9 target 4 label ""]
    edge[source 3 target 10 label ""]
    edge[source 9 target 11 label ""]
    edge[source 12 target 6 label ""]
]
""", name="SIMPLE BLOSSOM")

HONEY_SUCKLE = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 2 label ""]
    edge[source 0 target 3 label ""]
    edge[source 0 target 4 label ""]
    edge[source 0 target 5 label ""]
    edge[source 0 target 6 label ""]
    edge[source 6 target 7 label ""]
    edge[source 7 target 8 label ""]
    edge[source 8 target 6 label ""]
    edge[source 5 target 9 label ""]
    edge[source 9 target 10 label ""]
    edge[source 10 target 5 label ""]
    edge[source 4 target 11 label ""]
    edge[source 11 target 12 label ""]
    edge[source 12 target 4 label ""]
]
""", name="HONEY SUCKLE")

TRIAD = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    edge[source 0 target 4 label ""]
    edge[source 0 target 6 label ""]
    edge[source 1 target 5 label ""]
    edge[source 1 target 6 label ""]
    edge[source 2 target 4 label ""]
    edge[source 2 target 5 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 6 label ""]
]
""", name="TRIAD")

HAPPY_STAR = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    node[id 13 label "0"]
    node[id 14 label "0"]
    node[id 15 label "0"]
    edge[source 1 target 2 label ""]
    edge[source 3 target 4 label ""]
    edge[source 6 target 7 label ""]
    edge[source 3 target 8 label ""]
    edge[source 5 target 9 label ""]
    edge[source 6 target 10 label ""]
    edge[source 0 target 11 label ""]
    edge[source 1 target 12 label ""]
    edge[source 5 target 7 label ""]
    edge[source 2 target 0 label ""]
    edge[source 0 target 13 label ""]
    edge[source 13 target 2 label ""]
    edge[source 1 target 14 label ""]
    edge[source 14 target 2 label ""]
    edge[source 3 target 13 label ""]
    edge[source 13 target 4 label ""]
    edge[source 4 target 5 label ""]
    edge[source 4 target 7 label ""]
    edge[source 7 target 14 label ""]
    edge[source 14 target 6 label ""]
    edge[source 13 target 15 label ""]
    edge[source 7 target 15 label ""]
    edge[source 15 target 4 label ""]
    edge[source 15 target 14 label ""]
    edge[source 15 target 2 label ""]
]
""", name="HAPPY STAR")

BEACON = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    edge[source 0 target 6 label ""]
    edge[source 1 target 2 label ""]
    edge[source 1 target 4 label ""]
    edge[source 2 target 5 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 6 label ""]
    edge[source 4 target 5 label ""]
    edge[source 4 target 6 label ""]
]
""", name="BEACON")

TEDDY_BEAR = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    edge[source 0 target 4 label ""]
    edge[source 0 target 6 label ""]
    edge[source 1 target 2 label ""]
    edge[source 1 target 5 label ""]
    edge[source 1 target 6 label ""]
    edge[source 2 target 5 label ""]
    edge[source 2 target 6 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 6 label ""]
]
""", name="TEDDY BEAR")

MOSQUITO = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    edge[source 0 target 5 label ""]
    edge[source 0 target 7 label ""]
    edge[source 0 target 9 label ""]
    edge[source 1 target 8 label ""]
    edge[source 2 target 5 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 3 target 9 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
    edge[source 6 target 9 label ""]
]
""", name="MOSQUITO")

BROKEN_TREE = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 8 label ""]
    edge[source 0 target 9 label ""]
    edge[source 1 target 4 label ""]
    edge[source 1 target 7 label ""]
    edge[source 2 target 5 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 3 target 8 label ""]
    edge[source 3 target 9 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
    edge[source 6 target 9 label ""]
]
""", name="BROKEN TREE")

HORIZON = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    edge[source 0 target 3 label ""]
    edge[source 1 target 4 label ""]
    edge[source 2 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 3 target 9 label ""]
    edge[source 4 target 7 label ""]
    edge[source 5 target 7 label ""]
    edge[source 5 target 8 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
    edge[source 6 target 9 label ""]
    edge[source 7 target 8 label ""]
    edge[source 7 target 9 label ""]
]
""", name="HORIZON")

DRAGON = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    edge[source 0 target 7 label ""]
    edge[source 1 target 4 label ""]
    edge[source 2 target 5 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 8 label ""]
    edge[source 3 target 9 label ""]
    edge[source 5 target 8 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
    edge[source 6 target 9 label ""]
    edge[source 7 target 9 label ""]
]
""", name="DRAGON")

TREE = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    edge[source 0 target 5 label ""]
    edge[source 1 target 2 label ""]
    edge[source 1 target 3 label ""]
    edge[source 1 target 4 label ""]
    edge[source 2 target 3 label ""]
    edge[source 3 target 8 label ""]
    edge[source 3 target 9 label ""]
    edge[source 4 target 7 label ""]
    edge[source 4 target 8 label ""]
    edge[source 5 target 8 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
    edge[source 6 target 9 label ""]
    edge[source 7 target 8 label ""]
    edge[source 8 target 9 label ""]
]
""", name="TREE")

MASK = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    edge[source 0 target 4 label ""]
    edge[source 1 target 2 label ""]
    edge[source 1 target 7 label ""]
    edge[source 1 target 9 label ""]
    edge[source 2 target 5 label ""]
    edge[source 2 target 7 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 3 target 8 label ""]
    edge[source 3 target 9 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
    edge[source 6 target 9 label ""]
    edge[source 7 target 9 label ""]
    edge[source 8 target 9 label ""]
]
""", name="MASK")

SHALLOW_GRAVE = graphGMLString("""
graph [
        node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    edge[source 0 target 5 label ""]
    edge[source 1 target 2 label ""]
    edge[source 1 target 4 label ""]
    edge[source 1 target 8 label ""]
    edge[source 1 target 9 label ""]
    edge[source 2 target 4 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 3 target 8 label ""]
    edge[source 3 target 9 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
    edge[source 6 target 9 label ""]
    edge[source 7 target 8 label ""]
]
""", name="SHALLOW GRAVE")

KITE = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 5 label ""]
    edge[source 1 target 8 label ""]
    edge[source 1 target 9 label ""]
    edge[source 2 target 4 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 3 target 8 label ""]
    edge[source 5 target 7 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
    edge[source 6 target 9 label ""]
    edge[source 8 target 9 label ""]
]
""", name="KITE")

DOUBLE_CAP = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 2 label ""]
    edge[source 0 target 3 label ""]
    edge[source 0 target 5 label ""]
    edge[source 2 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 3 target 8 label ""]
    edge[source 4 target 5 label ""]
    edge[source 4 target 7 label ""]
    edge[source 4 target 8 label ""]
    edge[source 5 target 9 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
    edge[source 6 target 9 label ""]
]
""", name="DOUBLE CAP")

JUG = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 3 label ""]
    edge[source 0 target 4 label ""]
    edge[source 1 target 4 label ""]
    edge[source 2 target 4 label ""]
    edge[source 2 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 3 target 8 label ""]
    edge[source 4 target 7 label ""]
    edge[source 4 target 8 label ""]
    edge[source 5 target 9 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
    edge[source 6 target 9 label ""]
]
""", name="JUG")

BULB = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    edge[source 0 target 4 label ""]
    edge[source 1 target 5 label ""]
    edge[source 2 target 4 label ""]
    edge[source 2 target 5 label ""]
    edge[source 2 target 7 label ""]
    edge[source 2 target 9 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 3 target 8 label ""]
    edge[source 3 target 9 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
    edge[source 6 target 9 label ""]
]
""", name="BULB")

CONFLUX = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 3 label ""]
    edge[source 1 target 5 label ""]
    edge[source 10 target 11 label ""]
    edge[source 10 target 12 label ""]
    edge[source 10 target 4 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 6 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 6 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 5 target 8 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
    edge[source 7 target 8 label ""]
]
""", name="CONFLUX")

SOLUMN_TREE = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 10 label ""]
    edge[source 0 target 11 label ""]
    edge[source 1 target 8 label ""]
    edge[source 10 target 12 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 3 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 3 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 4 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 6 label ""]
    edge[source 3 target 7 label ""]
    edge[source 5 target 6 label ""]
    edge[source 5 target 7 label ""]
    edge[source 5 target 8 label ""]
    edge[source 7 target 8 label ""]
]
""", name="SOLUMN TREE")

NEPTUNE = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 1 target 2 label ""]
    edge[source 2 target 3 label ""]
    edge[source 3 target 4 label ""]
    edge[source 4 target 5 label ""]
    edge[source 5 target 0 label ""]
    edge[source 0 target 6 label ""]
    edge[source 6 target 7 label ""]
    edge[source 7 target 8 label ""]
    edge[source 8 target 9 label ""]
    edge[source 9 target 1 label ""]
    edge[source 1 target 10 label ""]
    edge[source 11 target 0 label ""]
    edge[source 10 target 12 label ""]
    edge[source 12 target 11 label ""]
]
""", name="NEPTUNE")

TANGLE = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 11 label ""]
    edge[source 0 target 12 label ""]
    edge[source 0 target 2 label ""]
    edge[source 0 target 7 label ""]
    edge[source 0 target 8 label ""]
    edge[source 10 target 3 label ""]
    edge[source 10 target 6 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 4 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 6 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 4 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 3 target 8 label ""]
    edge[source 4 target 5 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
]
""", name="TANGLE")

SUN_SPIRE = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 3 label ""]
    edge[source 1 target 2 label ""]
    edge[source 1 target 4 label ""]
    edge[source 10 target 12 label ""]
    edge[source 10 target 8 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 7 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 6 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 5 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 4 target 5 label ""]
    edge[source 4 target 7 label ""]
    edge[source 5 target 6 label ""]
    edge[source 5 target 7 label ""]
    edge[source 6 target 7 label ""]
]
""", name="SUN SPIRE")

OBSERVE = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 3 label ""]
    edge[source 0 target 5 label ""]
    edge[source 1 target 2 label ""]
    edge[source 1 target 3 label ""]
    edge[source 1 target 4 label ""]
    edge[source 10 target 12 label ""]
    edge[source 10 target 3 label ""]
    edge[source 10 target 6 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 3 label ""]
    edge[source 11 target 4 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 6 label ""]
    edge[source 12 target 7 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 3 label ""]
    edge[source 2 target 4 label ""]
    edge[source 3 target 7 label ""]
    edge[source 5 target 8 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
]
""", name="OBSERVE")

UNICORN = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]

    edge[source 0 target 2 label ""]
    edge[source 0 target 5 label ""]
    edge[source 1 target 4 label ""]
    edge[source 10 target 12 label ""]
    edge[source 10 target 7 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 8 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 6 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 6 label ""]
    edge[source 2 target 8 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 6 label ""]
    edge[source 3 target 7 label ""]
    edge[source 3 target 8 label ""]
    edge[source 5 target 8 label ""]
    edge[source 6 target 8 label ""]
    edge[source 7 target 8 label ""]
]
""", name="UNICORN")

BALLOON = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 4 label ""]
    edge[source 1 target 2 label ""]
    edge[source 1 target 5 label ""]
    edge[source 1 target 7 label ""]
    edge[source 10 target 11 label ""]
    edge[source 10 target 3 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 6 label ""]
    edge[source 11 target 8 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 6 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 7 label ""]
    edge[source 2 target 8 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 8 label ""]
    edge[source 5 target 8 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
]
""", name="BALLOON")

SCHOOL_TIME = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 4 label ""]
    edge[source 0 target 5 label ""]
    edge[source 1 target 4 label ""]
    edge[source 1 target 5 label ""]
    edge[source 10 target 11 label ""]
    edge[source 10 target 12 label ""]
    edge[source 10 target 7 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 12 label ""]
    edge[source 11 target 6 label ""]
    edge[source 11 target 8 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 7 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 4 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 6 label ""]
    edge[source 3 target 8 label ""]
]
""", name="SCHOOL TIME")

IN_CAMERA = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 5 label ""]
    edge[source 1 target 4 label ""]
    edge[source 10 target 7 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 12 label ""]
    edge[source 11 target 3 label ""]
    edge[source 11 target 6 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 6 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 7 label ""]
    edge[source 2 target 8 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 8 label ""]
    edge[source 5 target 7 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
]
""", name="IN CAMERA")

QUIET_MUSIC = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 5 label ""]
    edge[source 1 target 2 label ""]
    edge[source 1 target 8 label ""]
    edge[source 10 target 3 label ""]
    edge[source 10 target 6 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 3 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 2 label ""]
    edge[source 12 target 3 label ""]
    edge[source 12 target 4 label ""]
    edge[source 12 target 6 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 4 label ""]
    edge[source 2 target 8 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 3 target 8 label ""]
    edge[source 4 target 7 label ""]
    edge[source 4 target 8 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
]
""", name="QUIET MUSIC")

FALLEN_FRIEND = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 4 label ""]
    edge[source 1 target 7 label ""]
    edge[source 10 target 3 label ""]
    edge[source 10 target 7 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 12 label ""]
    edge[source 11 target 3 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 6 label ""]
    edge[source 12 target 7 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 8 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 8 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
]
""", name="FALLEN FRIEND")

WATER_LILY = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 5 label ""]
    edge[source 1 target 7 label ""]
    edge[source 1 target 8 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 3 label ""]
    edge[source 11 target 6 label ""]
    edge[source 11 target 8 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 3 label ""]
    edge[source 12 target 8 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 4 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 3 target 8 label ""]
    edge[source 5 target 8 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
    edge[source 7 target 8 label ""]
]
""", name="WATER LILY")

FLOWER_CANCER = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 2 label ""]
    edge[source 0 target 5 label ""]
    edge[source 0 target 7 label ""]
    edge[source 1 target 4 label ""]
    edge[source 10 target 11 label ""]
    edge[source 10 target 12 label ""]
    edge[source 10 target 6 label ""]
    edge[source 10 target 7 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 12 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 6 label ""]
    edge[source 12 target 8 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 5 label ""]
    edge[source 2 target 7 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 6 label ""]
    edge[source 3 target 8 label ""]
    edge[source 7 target 8 label ""]
]
""", name="FLOWER CANCER")

PLAGUE_DOCTOR = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 2 label ""]
    edge[source 0 target 3 label ""]
    edge[source 0 target 4 label ""]
    edge[source 1 target 5 label ""]
    edge[source 10 target 12 label ""]
    edge[source 10 target 4 label ""]
    edge[source 10 target 5 label ""]
    edge[source 10 target 6 label ""]
    edge[source 10 target 7 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 6 label ""]
    edge[source 11 target 8 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 3 label ""]
    edge[source 12 target 6 label ""]
    edge[source 12 target 7 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 4 label ""]
    edge[source 3 target 4 label ""]
    edge[source 5 target 7 label ""]
    edge[source 5 target 8 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
    edge[source 7 target 8 label ""]
]
""", name="PLAGUE DOCTOR")

TORN_CROSS = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 4 label ""]
    edge[source 1 target 3 label ""]
    edge[source 10 target 11 label ""]
    edge[source 10 target 6 label ""]
    edge[source 10 target 7 label ""]
    edge[source 10 target 8 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 5 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 7 label ""]
    edge[source 4 target 6 label ""]
    edge[source 5 target 8 label ""]
    edge[source 6 target 8 label ""]
    edge[source 7 target 8 label ""]
]
""", name="TORN CROSS")

TORN_FLOWER = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 4 label ""]
    edge[source 0 target 5 label ""]
    edge[source 1 target 5 label ""]
    edge[source 10 target 6 label ""]
    edge[source 10 target 8 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 6 label ""]
    edge[source 12 target 7 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 3 label ""]
    edge[source 3 target 6 label ""]
    edge[source 4 target 6 label ""]
    edge[source 4 target 8 label ""]
    edge[source 5 target 6 label ""]
    edge[source 6 target 7 label ""]
]
""", name="TORN FLOWER")

BALLET = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 10 label ""]
    edge[source 0 target 11 label ""]
    edge[source 0 target 6 label ""]
    edge[source 1 target 4 label ""]
    edge[source 10 target 12 label ""]
    edge[source 10 target 3 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 3 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 2 label ""]
    edge[source 12 target 9 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 7 label ""]
    edge[source 3 target 8 label ""]
    edge[source 5 target 6 label ""]
    edge[source 5 target 7 label ""]
    edge[source 5 target 8 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
]
""", name="BALLET")

CHURCH_CELLAR = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 5 label ""]
    edge[source 1 target 11 label ""]
    edge[source 1 target 5 label ""]
    edge[source 10 target 3 label ""]
    edge[source 10 target 6 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 12 label ""]
    edge[source 11 target 6 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 3 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 4 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
]
""", name="CHURCH CELLAR")

SENTINEL  = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 5 label ""]
    edge[source 1 target 4 label ""]
    edge[source 10 target 12 label ""]
    edge[source 10 target 6 label ""]
    edge[source 10 target 7 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 6 label ""]
    edge[source 11 target 7 label ""]
    edge[source 11 target 8 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 6 label ""]
    edge[source 2 target 7 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 3 target 8 label ""]
    edge[source 5 target 6 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
]
""", name="SENTINEL ")

LANDER = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 11 label ""]
    edge[source 0 target 12 label ""]
    edge[source 0 target 2 label ""]
    edge[source 1 target 4 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 3 label ""]
    edge[source 11 target 6 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 3 label ""]
    edge[source 12 target 6 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 6 label ""]
    edge[source 2 target 7 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 6 label ""]
    edge[source 3 target 8 label ""]
    edge[source 5 target 6 label ""]
    edge[source 5 target 7 label ""]
    edge[source 5 target 8 label ""]
    edge[source 6 target 7 label ""]
]
""", name="LANDER")

SHUTTLE = graphGMLString("""
graph [    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    node[id 13 label "0"]
    node[id 14 label "0"]
    node[id 15 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 2 label ""]
    edge[source 0 target 6 label ""]
    edge[source 0 target 7 label ""]
    edge[source 1 target 5 label ""]
    edge[source 10 target 15 label ""]
    edge[source 10 target 8 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 13 label ""]
    edge[source 11 target 14 label ""]
    edge[source 11 target 15 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 13 label ""]
    edge[source 12 target 14 label ""]
    edge[source 12 target 15 label ""]
    edge[source 13 target 14 label ""]
    edge[source 14 target 15 label ""]
    edge[source 14 target 9 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 6 label ""]
    edge[source 3 target 8 label ""]
    edge[source 6 target 9 label ""]
    edge[source 7 target 8 label ""]
    edge[source 7 target 9 label ""]
    edge[source 8 target 9 label ""]
]
""", name="SHUTTLE")

HYACINTH = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 4 label ""]
    edge[source 1 target 2 label ""]
    edge[source 1 target 3 label ""]
    edge[source 1 target 7 label ""]
    edge[source 1 target 8 label ""]
    edge[source 10 target 12 label ""]
    edge[source 10 target 3 label ""]
    edge[source 10 target 6 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 12 label ""]
    edge[source 11 target 7 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 3 label ""]
    edge[source 12 target 4 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 3 label ""]
    edge[source 2 target 7 label ""]
    edge[source 5 target 6 label ""]
    edge[source 5 target 7 label ""]
    edge[source 5 target 8 label ""]
    edge[source 6 target 8 label ""]
    edge[source 7 target 8 label ""]
]
""", name="HYACINTH")

VIL_TOWER = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    node[id 13 label "0"]
    node[id 14 label "0"]
    node[id 15 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 2 label ""]
    edge[source 0 target 3 label ""]
    edge[source 0 target 4 label ""]
    edge[source 0 target 5 label ""]
    edge[source 10 target 13 label ""]
    edge[source 10 target 7 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 15 label ""]
    edge[source 11 target 6 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 13 label ""]
    edge[source 12 target 14 label ""]
    edge[source 12 target 15 label ""]
    edge[source 13 target 15 label ""]
    edge[source 13 target 9 label ""]
    edge[source 14 target 9 label ""]
    edge[source 2 target 3 label ""]
    edge[source 2 target 4 label ""]
    edge[source 2 target 5 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 6 label ""]
    edge[source 4 target 5 label ""]
    edge[source 4 target 8 label ""]
    edge[source 5 target 7 label ""]
    edge[source 6 target 8 label ""]
    edge[source 6 target 9 label ""]
    edge[source 8 target 9 label ""]
]
""", name="VIL TOWER")

PLATEAU = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 4 label ""]
    edge[source 1 target 11 label ""]
    edge[source 1 target 12 label ""]
    edge[source 1 target 8 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 3 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 3 label ""]
    edge[source 12 target 9 label ""]
    edge[source 2 target 7 label ""]
    edge[source 2 target 8 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 6 label ""]
    edge[source 3 target 8 label ""]
    edge[source 5 target 6 label ""]
    edge[source 5 target 7 label ""]
    edge[source 5 target 8 label ""]
    edge[source 6 target 7 label ""]
]
""", name="PLATEAU")

SPLIT_FISH = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    node[id 13 label "0"]
    node[id 14 label "0"]
    node[id 15 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 2 label ""]
    edge[source 0 target 4 label ""]
    edge[source 0 target 7 label ""]
    edge[source 1 target 2 label ""]
    edge[source 10 target 5 label ""]
    edge[source 10 target 6 label ""]
    edge[source 10 target 8 label ""]
    edge[source 11 target 5 label ""]
    edge[source 11 target 6 label ""]
    edge[source 11 target 8 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 13 label ""]
    edge[source 12 target 14 label ""]
    edge[source 12 target 15 label ""]
    edge[source 13 target 3 label ""]
    edge[source 13 target 6 label ""]
    edge[source 14 target 15 label ""]
    edge[source 14 target 3 label ""]
    edge[source 15 target 6 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 6 target 7 label ""]
    edge[source 8 target 9 label ""]
]
""", name="SPLIT FISH")

CHURCH = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 11 label ""]
    edge[source 0 target 12 label ""]
    edge[source 0 target 2 label ""]
    edge[source 0 target 4 label ""]
    edge[source 1 target 3 label ""]
    edge[source 10 target 2 label ""]
    edge[source 10 target 6 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 7 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 6 label ""]
    edge[source 12 target 7 label ""]
    edge[source 12 target 9 label ""]
    edge[source 3 target 6 label ""]
    edge[source 3 target 7 label ""]
    edge[source 4 target 8 label ""]
    edge[source 5 target 6 label ""]
    edge[source 5 target 7 label ""]
    edge[source 5 target 8 label ""]
    edge[source 6 target 7 label ""]
]
""", name="CHURCH")

FORTRESS = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    node[id 13 label "0"]
    node[id 14 label "0"]
    node[id 15 label "0"]
    edge[source 0 target 3 label ""]
    edge[source 1 target 5 label ""]
    edge[source 10 target 6 label ""]
    edge[source 10 target 7 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 13 label ""]
    edge[source 11 target 14 label ""]
    edge[source 11 target 6 label ""]
    edge[source 11 target 8 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 13 label ""]
    edge[source 12 target 14 label ""]
    edge[source 12 target 15 label ""]
    edge[source 13 target 9 label ""]
    edge[source 14 target 7 label ""]
    edge[source 2 target 4 label ""]
    edge[source 2 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 4 target 6 label ""]
    edge[source 4 target 8 label ""]
    edge[source 5 target 7 label ""]
    edge[source 6 target 8 label ""]
    edge[source 7 target 8 label ""]
]
""", name="FORTRESS")

FABERGE = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    node[id 13 label "0"]
    node[id 14 label "0"]
    node[id 15 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 11 label ""]
    edge[source 0 target 14 label ""]
    edge[source 0 target 15 label ""]
    edge[source 0 target 2 label ""]
    edge[source 0 target 4 label ""]
    edge[source 0 target 8 label ""]
    edge[source 1 target 4 label ""]
    edge[source 10 target 3 label ""]
    edge[source 10 target 6 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 6 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 13 label ""]
    edge[source 12 target 14 label ""]
    edge[source 12 target 15 label ""]
    edge[source 14 target 3 label ""]
    edge[source 14 target 9 label ""]
    edge[source 15 target 3 label ""]
    edge[source 15 target 9 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 4 target 7 label ""]
    edge[source 4 target 8 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
]
""", name="FABERGE")

AORTA = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    node[id 13 label "0"]
    node[id 14 label "0"]
    node[id 15 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 10 label ""]
    edge[source 0 target 11 label ""]
    edge[source 0 target 14 label ""]
    edge[source 0 target 2 label ""]
    edge[source 0 target 5 label ""]
    edge[source 0 target 7 label ""]
    edge[source 1 target 4 label ""]
    edge[source 10 target 11 label ""]
    edge[source 10 target 14 label ""]
    edge[source 10 target 3 label ""]
    edge[source 10 target 6 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 13 label ""]
    edge[source 12 target 14 label ""]
    edge[source 12 target 15 label ""]
    edge[source 13 target 3 label ""]
    edge[source 13 target 6 label ""]
    edge[source 14 target 15 label ""]
    edge[source 14 target 3 label ""]
    edge[source 14 target 9 label ""]
    edge[source 15 target 9 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
]
""", name="AORTA")

LONG_TOWER = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    node[id 13 label "0"]
    node[id 14 label "0"]
    node[id 15 label "0"]
    edge[source 0 target 5 label ""]
    edge[source 1 target 2 label ""]
    edge[source 1 target 4 label ""]
    edge[source 10 target 11 label ""]
    edge[source 10 target 13 label ""]
    edge[source 10 target 14 label ""]
    edge[source 10 target 15 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 15 label ""]
    edge[source 11 target 6 label ""]
    edge[source 11 target 7 label ""]
    edge[source 11 target 8 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 13 label ""]
    edge[source 12 target 14 label ""]
    edge[source 12 target 15 label ""]
    edge[source 14 target 9 label ""]
    edge[source 15 target 9 label ""]
    edge[source 2 target 4 label ""]
    edge[source 2 target 7 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 6 label ""]
    edge[source 3 target 7 label ""]
    edge[source 3 target 8 label ""]
    edge[source 6 target 9 label ""]
    edge[source 8 target 9 label ""]
]
""", name="LONG TOWER")

NOBLE_BUST = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 10 label ""]
    edge[source 0 target 2 label ""]
    edge[source 0 target 4 label ""]
    edge[source 0 target 7 label ""]
    edge[source 0 target 8 label ""]
    edge[source 1 target 2 label ""]
    edge[source 10 target 11 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 6 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 3 label ""]
    edge[source 12 target 6 label ""]
    edge[source 12 target 9 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 8 label ""]
    edge[source 5 target 7 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
]
""", name="NOBLE BUST")

KIND_HEART = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    node[id 13 label "0"]
    node[id 14 label "0"]
    node[id 15 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 10 label ""]
    edge[source 0 target 11 label ""]
    edge[source 0 target 13 label ""]
    edge[source 0 target 15 label ""]
    edge[source 0 target 2 label ""]
    edge[source 10 target 6 label ""]
    edge[source 10 target 8 label ""]
    edge[source 11 target 3 label ""]
    edge[source 11 target 8 label ""]
    edge[source 12 target 13 label ""]
    edge[source 12 target 14 label ""]
    edge[source 12 target 15 label ""]
    edge[source 13 target 6 label ""]
    edge[source 14 target 15 label ""]
    edge[source 14 target 6 label ""]
    edge[source 2 target 5 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 7 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 9 label ""]
    edge[source 7 target 9 label ""]
    edge[source 8 target 9 label ""]
]
""", name="KIND HEART")

RIBBON = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    node[id 13 label "0"]
    node[id 14 label "0"]
    node[id 15 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 15 label ""]
    edge[source 0 target 2 label ""]
    edge[source 0 target 7 label ""]
    edge[source 1 target 2 label ""]
    edge[source 10 target 3 label ""]
    edge[source 10 target 8 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 3 label ""]
    edge[source 11 target 6 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 13 label ""]
    edge[source 12 target 14 label ""]
    edge[source 12 target 15 label ""]
    edge[source 13 target 15 label ""]
    edge[source 13 target 6 label ""]
    edge[source 14 target 6 label ""]
    edge[source 14 target 9 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 8 label ""]
    edge[source 4 target 5 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
]
""", name="RIBBON")

UPTURND_BLOSSOM = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    node[id 13 label "0"]
    node[id 14 label "0"]
    node[id 15 label "0"]
    edge[source 0 target 10 label ""]
    edge[source 0 target 11 label ""]
    edge[source 1 target 5 label ""]
    edge[source 1 target 6 label ""]
    edge[source 10 target 3 label ""]
    edge[source 10 target 5 label ""]
    edge[source 10 target 8 label ""]
    edge[source 11 target 8 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 13 label ""]
    edge[source 12 target 14 label ""]
    edge[source 12 target 15 label ""]
    edge[source 13 target 14 label ""]
    edge[source 13 target 15 label ""]
    edge[source 13 target 5 label ""]
    edge[source 13 target 6 label ""]
    edge[source 13 target 7 label ""]
    edge[source 14 target 7 label ""]
    edge[source 15 target 6 label ""]
    edge[source 2 target 4 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 6 label ""]
    edge[source 3 target 7 label ""]
    edge[source 3 target 9 label ""]
    edge[source 5 target 6 label ""]
    edge[source 8 target 9 label ""]
]
""", name="UPTURND BLOSSOM")

SUBWAY = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    node[id 13 label "0"]
    node[id 14 label "0"]
    node[id 15 label "0"]
    node[id 16 label "0"]
    node[id 17 label "0"]
    node[id 18 label "0"]
    node[id 19 label "0"]
    node[id 20 label "0"]
    node[id 21 label "0"]
    edge[source 0 target 1 label ""]
    edge[source 0 target 13 label ""]
    edge[source 0 target 16 label ""]
    edge[source 0 target 2 label ""]
    edge[source 0 target 20 label ""]
    edge[source 0 target 5 label ""]
    edge[source 0 target 6 label ""]
    edge[source 10 target 11 label ""]
    edge[source 10 target 12 label ""]
    edge[source 10 target 13 label ""]
    edge[source 11 target 3 label ""]
    edge[source 13 target 3 label ""]
    edge[source 14 target 15 label ""]
    edge[source 14 target 16 label ""]
    edge[source 14 target 17 label ""]
    edge[source 15 target 3 label ""]
    edge[source 15 target 4 label ""]
    edge[source 16 target 7 label ""]
    edge[source 17 target 3 label ""]
    edge[source 17 target 4 label ""]
    edge[source 17 target 7 label ""]
    edge[source 18 target 19 label ""]
    edge[source 18 target 20 label ""]
    edge[source 18 target 21 label ""]
    edge[source 20 target 3 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 6 label ""]
    edge[source 3 target 9 label ""]
    edge[source 4 target 5 label ""]
    edge[source 4 target 6 label ""]
    edge[source 4 target 8 label ""]
    edge[source 4 target 9 label ""]
    edge[source 7 target 8 label ""]
    edge[source 7 target 9 label ""]
]
""", name="SUBWAY")

TURKEY = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    node[id 13 label "0"]
    node[id 14 label "0"]
    node[id 15 label "0"]
    edge[source 0 target 4 label ""]
    edge[source 1 target 5 label ""]
    edge[source 1 target 7 label ""]
    edge[source 10 target 14 label ""]
    edge[source 10 target 3 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 2 label ""]
    edge[source 11 target 6 label ""]
    edge[source 11 target 9 label ""]
    edge[source 12 target 13 label ""]
    edge[source 12 target 14 label ""]
    edge[source 12 target 15 label ""]
    edge[source 13 target 14 label ""]
    edge[source 13 target 15 label ""]
    edge[source 13 target 2 label ""]
    edge[source 13 target 6 label ""]
    edge[source 13 target 9 label ""]
    edge[source 14 target 2 label ""]
    edge[source 14 target 9 label ""]
    edge[source 2 target 5 label ""]
    edge[source 2 target 8 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 5 label ""]
    edge[source 3 target 8 label ""]
    edge[source 5 target 7 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
]
""", name="TURKEY")

FLOTSAM = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    node[id 13 label "0"]
    node[id 14 label "0"]
    node[id 15 label "0"]
    node[id 16 label "0"]
    node[id 17 label "0"]
    node[id 18 label "0"]
    edge[source 0 target 13 label ""]
    edge[source 0 target 2 label ""]
    edge[source 0 target 6 label ""]
    edge[source 1 target 10 label ""]
    edge[source 10 target 3 label ""]
    edge[source 10 target 8 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 8 label ""]
    edge[source 12 target 18 label ""]
    edge[source 12 target 5 label ""]
    edge[source 13 target 14 label ""]
    edge[source 13 target 16 label ""]
    edge[source 13 target 17 label ""]
    edge[source 13 target 3 label ""]
    edge[source 13 target 5 label ""]
    edge[source 13 target 6 label ""]
    edge[source 14 target 16 label ""]
    edge[source 14 target 18 label ""]
    edge[source 14 target 3 label ""]
    edge[source 14 target 6 label ""]
    edge[source 15 target 16 label ""]
    edge[source 15 target 17 label ""]
    edge[source 15 target 18 label ""]
    edge[source 16 target 18 label ""]
    edge[source 2 target 4 label ""]
    edge[source 3 target 4 label ""]
    edge[source 3 target 6 label ""]
    edge[source 3 target 7 label ""]
    edge[source 4 target 6 label ""]
    edge[source 5 target 6 label ""]
    edge[source 5 target 7 label ""]
    edge[source 6 target 7 label ""]
    edge[source 8 target 9 label ""]
]
""", name="FLOTSAM")

LANDSCAPE = graphGMLString("""
graph [
    node[id 0 label "0"]
    node[id 1 label "0"]
    node[id 2 label "0"]
    node[id 3 label "0"]
    node[id 4 label "0"]
    node[id 5 label "0"]
    node[id 6 label "0"]
    node[id 7 label "0"]
    node[id 8 label "0"]
    node[id 9 label "0"]
    node[id 10 label "0"]
    node[id 11 label "0"]
    node[id 12 label "0"]
    node[id 13 label "0"]
    node[id 14 label "0"]
    node[id 15 label "0"]
    node[id 16 label "0"]
    node[id 17 label "0"]
    node[id 18 label "0"]
    edge[source 0 target 7 label ""]
    edge[source 1 target 10 label ""]
    edge[source 10 target 11 label ""]
    edge[source 10 target 12 label ""]
    edge[source 10 target 6 label ""]
    edge[source 10 target 7 label ""]
    edge[source 10 target 9 label ""]
    edge[source 11 target 13 label ""]
    edge[source 12 target 13 label ""]
    edge[source 12 target 16 label ""]
    edge[source 12 target 18 label ""]
    edge[source 13 target 14 label ""]
    edge[source 13 target 16 label ""]
    edge[source 13 target 17 label ""]
    edge[source 13 target 18 label ""]
    edge[source 13 target 9 label ""]
    edge[source 14 target 16 label ""]
    edge[source 15 target 16 label ""]
    edge[source 15 target 17 label ""]
    edge[source 15 target 18 label ""]
    edge[source 16 target 18 label ""]
    edge[source 2 target 3 label ""]
    edge[source 2 target 4 label ""]
    edge[source 2 target 5 label ""]
    edge[source 3 target 4 label ""]
    edge[source 4 target 5 label ""]
    edge[source 5 target 8 label ""]
    edge[source 6 target 7 label ""]
    edge[source 6 target 8 label ""]
    edge[source 6 target 9 label ""]
]
""", name="LANDSCAPE")
